<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\*;

class Badge extends Model
{
    protected $fillable = [
    'name',
    'name_ar',
    'description',
    'description_ar',
    'icon',
    'color',
    'category',
    'criteria',
    'points',
    'rarity',
    'is_active'
];

    protected $casts = [
    'criteria' => 'array',
    'is_active' => 'boolean',
    'points' => 'integer'
];

    public function studentBadges()
    {
        return $this->hasMany(StudentBadge::class);
    }

    public function students()
    {
        return $this->belongsToMany(Student::class, 'student_badges')->withPivot('earned_at', 'progress')->withTimestamps();
    }

    // Badge Categories
    const CATEGORY_ATTENDANCE = 'attendance';
    const CATEGORY_ACADEMIC = 'academic';
    const CATEGORY_IMPROVEMENT = 'improvement';
    const CATEGORY_SPECIAL = 'special';
    const CATEGORY_SOCIAL = 'social';

    // Badge Rarity
    const RARITY_COMMON = 'common';
    const RARITY_RARE = 'rare';
    const RARITY_EPIC = 'epic';
    const RARITY_LEGENDARY = 'legendary';

    public static function getDefaultBadges(): array
    {
        return [
            // ATTENDANCE BADGES (15 badges)
            [
                'name' => 'Welcome to School',
                'name_ar' => 'مرحبا بك في المدرسة',
                'description' => 'Attend your first day of school',
                'description_ar' => 'حضور أول يوم في المدرسة',
                'icon' => '🎒',
                'color' => '#4CAF50',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'attendance_days', 'value' => 1],
                'points' => 10,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Perfect Week',
                'name_ar' => 'أسبوع مثالي',
                'description' => '100% attendance for a week',
                'description_ar' => 'حضور 100٪ لمدة أسبوع',
                'icon' => '📅',
                'color' => '#2196F3',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'attendance_streak', 'value' => 5],
                'points' => 50,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Perfect Month',
                'name_ar' => 'شهر مثالي',
                'description' => '100% attendance for a month',
                'description_ar' => 'حضور 100٪ لمدة شهر',
                'icon' => '🗓️',
                'color' => '#FF9800',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'attendance_streak', 'value' => 20],
                'points' => 200,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Iron Will',
                'name_ar' => 'إرادة حديدية',
                'description' => '50 days perfect attendance',
                'description_ar' => '50 يوما من الحضور المثالي',
                'icon' => '💪',
                'color' => '#607D8B',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'attendance_streak', 'value' => 50],
                'points' => 500,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'Perfect Year',
                'name_ar' => 'سنة مثالية',
                'description' => '100% attendance for the entire year',
                'description_ar' => 'حضور 100٪ طوال العام',
                'icon' => '🏆',
                'color' => '#FFD700',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'attendance_days', 'value' => 180],
                'points' => 1000,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Early Bird',
                'name_ar' => 'الطائر المبكر',
                'description' => 'Arrive early 10 times',
                'description_ar' => 'الوصول مبكرا 10 مرات',
                'icon' => '🌅',
                'color' => '#FFC107',
                'category' => self::CATEGORY_ATTENDANCE,
                'criteria' => ['type' => 'early_arrivals', 'value' => 10],
                'points' => 100,
                'rarity' => self::RARITY_COMMON,
            ],

            // ACADEMIC EXCELLENCE BADGES (20 badges)
            [
                'name' => 'First Steps',
                'name_ar' => 'الخطوات الأولى',
                'description' => 'Submit your first assignment',
                'description_ar' => 'تقديم أول واجب',
                'icon' => '📝',
                'color' => '#4CAF50',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'assignments_submitted', 'value' => 1],
                'points' => 10,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Homework Hero',
                'name_ar' => 'بطل الواجبات',
                'description' => 'Submit 50 assignments',
                'description_ar' => 'تقديم 50 واجب',
                'icon' => '✏️',
                'color' => '#2196F3',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'assignments_submitted', 'value' => 50],
                'points' => 250,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Perfect Score',
                'name_ar' => 'درجة كاملة',
                'description' => 'Get 100% on any assignment',
                'description_ar' => 'الحصول على 100٪ في أي واجب',
                'icon' => '💯',
                'color' => '#F44336',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'perfect_scores', 'value' => 1],
                'points' => 100,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Perfectionist',
                'name_ar' => 'الكمالي',
                'description' => 'Get 100% on 10 assignments',
                'description_ar' => 'الحصول على 100٪ في 10 واجبات',
                'icon' => '⭐',
                'color' => '#FFD700',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'perfect_scores', 'value' => 10],
                'points' => 1000,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Excellence Master',
                'name_ar' => 'سيد التفوق',
                'description' => 'Maintain average above 90%',
                'description_ar' => 'الحفاظ على معدل أعلى من 90٪',
                'icon' => '🎓',
                'color' => '#9C27B0',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'average_above', 'value' => 90],
                'points' => 500,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'Good Student',
                'name_ar' => 'طالب جيد',
                'description' => 'Maintain average above 80%',
                'description_ar' => 'الحفاظ على معدل أعلى من 80٪',
                'icon' => '📚',
                'color' => '#3F51B5',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'average_above', 'value' => 80],
                'points' => 250,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Quick Learner',
                'name_ar' => 'سريع التعلم',
                'description' => 'Complete 5 quizzes with 85%+',
                'description_ar' => 'إكمال 5 اختبارات بنسبة 85٪+',
                'icon' => '🧠',
                'color' => '#00BCD4',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'quizzes_high_score', 'value' => 5],
                'points' => 150,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Math Wizard',
                'name_ar' => 'ساحر الرياضيات',
                'description' => 'Excel in Mathematics (90%+)',
                'description_ar' => 'التفوق في الرياضيات (90٪+)',
                'icon' => '🔢',
                'color' => '#E91E63',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'subject_average', 'subject' => 'math', 'value' => 90],
                'points' => 300,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'Science Star',
                'name_ar' => 'نجم العلوم',
                'description' => 'Excel in Science (90%+)',
                'description_ar' => 'التفوق في العلوم (90٪+)',
                'icon' => '🔬',
                'color' => '#009688',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'subject_average', 'subject' => 'science', 'value' => 90],
                'points' => 300,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'Language Master',
                'name_ar' => 'سيد اللغات',
                'description' => 'Excel in Languages (90%+)',
                'description_ar' => 'التفوق في اللغات (90٪+)',
                'icon' => '📖',
                'color' => '#795548',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'subject_average', 'subject' => 'language', 'value' => 90],
                'points' => 300,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'All-Rounder',
                'name_ar' => 'متعدد المواهب',
                'description' => 'Score 85%+ in all subjects',
                'description_ar' => 'تحقيق 85٪+ في جميع المواد',
                'icon' => '🌟',
                'color' => '#FF5722',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'all_subjects_above', 'value' => 85],
                'points' => 750,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Early Submission',
                'name_ar' => 'التسليم المبكر',
                'description' => 'Submit 10 assignments early',
                'description_ar' => 'تقديم 10 واجبات مبكرا',
                'icon' => '⏰',
                'color' => '#FF9800',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'early_submissions', 'value' => 10],
                'points' => 200,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Test Champion',
                'name_ar' => 'بطل الاختبارات',
                'description' => 'Score 90%+ on 5 exams',
                'description_ar' => 'تحقيق 90٪+ في 5 امتحانات',
                'icon' => '📋',
                'color' => '#673AB7',
                'category' => self::CATEGORY_ACADEMIC,
                'criteria' => ['type' => 'exams_high_score', 'value' => 5],
                'points' => 400,
                'rarity' => self::RARITY_EPIC,
            ],

            // IMPROVEMENT BADGES (10 badges)
            [
                'name' => 'Rising Star',
                'name_ar' => 'النجم الصاعد',
                'description' => 'Improve grade by 10%',
                'description_ar' => 'تحسين الدرجة بنسبة 10٪',
                'icon' => '📈',
                'color' => '#8BC34A',
                'category' => self::CATEGORY_IMPROVEMENT,
                'criteria' => ['type' => 'grade_improvement', 'value' => 10],
                'points' => 150,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Comeback King',
                'name_ar' => 'ملك العودة',
                'description' => 'Improve from below 60% to above 80%',
                'description_ar' => 'التحسين من أقل من 60٪ إلى أكثر من 80٪',
                'icon' => '🚀',
                'color' => '#F44336',
                'category' => self::CATEGORY_IMPROVEMENT,
                'criteria' => ['type' => 'comeback', 'from' => 60, 'to' => 80],
                'points' => 500,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Never Give Up',
                'name_ar' => 'لا تستسلم أبدا',
                'description' => 'Retry failed assignment and pass',
                'description_ar' => 'إعادة محاولة الواجب الفاشل والنجاح',
                'icon' => '💪',
                'color' => '#FF5722',
                'category' => self::CATEGORY_IMPROVEMENT,
                'criteria' => ['type' => 'retries_success', 'value' => 1],
                'points' => 100,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Most Improved',
                'name_ar' => 'الأكثر تحسنا',
                'description' => 'Biggest improvement in class',
                'description_ar' => 'أكبر تحسن في الصف',
                'icon' => '🏅',
                'color' => '#FFD700',
                'category' => self::CATEGORY_IMPROVEMENT,
                'criteria' => ['type' => 'top_improvement', 'rank' => 1],
                'points' => 600,
                'rarity' => self::RARITY_LEGENDARY,
            ],

            // SPECIAL ACHIEVEMENT BADGES (12 badges)
            [
                'name' => 'Champion',
                'name_ar' => 'البطل',
                'description' => 'Rank #1 in your class',
                'description_ar' => 'المرتبة الأولى في صفك',
                'icon' => '🥇',
                'color' => '#FFD700',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'class_rank', 'value' => 1],
                'points' => 1000,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Silver Medal',
                'name_ar' => 'الميدالية الفضية',
                'description' => 'Rank #2 in your class',
                'description_ar' => 'المرتبة الثانية في صفك',
                'icon' => '🥈',
                'color' => '#C0C0C0',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'class_rank', 'value' => 2],
                'points' => 750,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'Bronze Medal',
                'name_ar' => 'الميدالية البرونزية',
                'description' => 'Rank #3 in your class',
                'description_ar' => 'المرتبة الثالثة في صفك',
                'icon' => '🥉',
                'color' => '#CD7F32',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'class_rank', 'value' => 3],
                'points' => 500,
                'rarity' => self::RARITY_EPIC,
            ],
            [
                'name' => 'XP Master',
                'name_ar' => 'سيد النقاط',
                'description' => 'Earn 1000 XP',
                'description_ar' => 'كسب 1000 نقطة XP',
                'icon' => '⚡',
                'color' => '#FFEB3B',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'total_xp', 'value' => 1000],
                'points' => 100,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'XP Legend',
                'name_ar' => 'أسطورة النقاط',
                'description' => 'Earn 10000 XP',
                'description_ar' => 'كسب 10000 نقطة XP',
                'icon' => '💎',
                'color' => '#B9F2FF',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'total_xp', 'value' => 10000],
                'points' => 1000,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Level 10',
                'name_ar' => 'المستوى 10',
                'description' => 'Reach level 10',
                'description_ar' => 'الوصول إلى المستوى 10',
                'icon' => '🔟',
                'color' => '#03A9F4',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'level', 'value' => 10],
                'points' => 200,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Level 50',
                'name_ar' => 'المستوى 50',
                'description' => 'Reach level 50',
                'description_ar' => 'الوصول إلى المستوى 50',
                'icon' => '5️⃣0️⃣',
                'color' => '#9C27B0',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'level', 'value' => 50],
                'points' => 1000,
                'rarity' => self::RARITY_LEGENDARY,
            ],
            [
                'name' => 'Veteran',
                'name_ar' => 'المخضرم',
                'description' => 'Complete 3 school years',
                'description_ar' => 'إكمال 3 سنوات مدرسية',
                'icon' => '🎖️',
                'color' => '#795548',
                'category' => self::CATEGORY_SPECIAL,
                'criteria' => ['type' => 'years_completed', 'value' => 3],
                'points' => 800,
                'rarity' => self::RARITY_EPIC,
            ],

            // SOCIAL BADGES (8 badges)
            [
                'name' => 'Helpful Peer',
                'name_ar' => 'الزميل المساعد',
                'description' => 'Help 10 classmates',
                'description_ar' => 'مساعدة 10 زملاء',
                'icon' => '🤝',
                'color' => '#4CAF50',
                'category' => self::CATEGORY_SOCIAL,
                'criteria' => ['type' => 'peers_helped', 'value' => 10],
                'points' => 200,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Study Group Leader',
                'name_ar' => 'قائد مجموعة الدراسة',
                'description' => 'Create and lead a study group',
                'description_ar' => 'إنشاء وقيادة مجموعة دراسية',
                'icon' => '👥',
                'color' => '#2196F3',
                'category' => self::CATEGORY_SOCIAL,
                'criteria' => ['type' => 'study_groups_led', 'value' => 1],
                'points' => 150,
                'rarity' => self::RARITY_COMMON,
            ],
            [
                'name' => 'Team Player',
                'name_ar' => 'لاعب الفريق',
                'description' => 'Complete 5 group projects',
                'description_ar' => 'إكمال 5 مشاريع جماعية',
                'icon' => '🎯',
                'color' => '#FF9800',
                'category' => self::CATEGORY_SOCIAL,
                'criteria' => ['type' => 'group_projects', 'value' => 5],
                'points' => 250,
                'rarity' => self::RARITY_RARE,
            ],
            [
                'name' => 'Mentor',
                'name_ar' => 'المرشد',
                'description' => 'Tutor 5 students successfully',
                'description_ar' => 'توجيه 5 طلاب بنجاح',
                'icon' => '🎓',
                'color' => '#9C27B0',
                'category' => self::CATEGORY_SOCIAL,
                'criteria' => ['type' => 'tutoring_sessions', 'value' => 5],
                'points' => 400,
                'rarity' => self::RARITY_EPIC,
            ],
        ];
    }
}
